language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 1.9.3
- 2.0
- 2.1
- 2.2
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-memory-checks.gemspec
- gem install sensu-plugins-memory-checks-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: TgMN+aURCSc0ilnRDJpQ3ySfEriGppMn5onctJJWN6ghReaKe8faXjcB/RWljfIBQgxkijy2svMgN+y6cRyii6dTfnFnZY4yUO+u6+HU5QNzb5uVbn2MKU5KfpsQFYwToPSKbQ1YcvA39U67sS4aRVf0TsrPoQfXZxOeLytNtz8=
  gem: sensu-plugins-memory-checks
  on:
    tags: true
    all_branches: true
    rvm: 1.9.3
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    repo: sensu-plugins/sensu-plugins-memory-checks
